SubOrDub=sub
SkipFiller=true
RofiSelection=true
ScoreOnCompletion=true
AlternateScreen=true
DiscordPresence=true
Player=mpv
PercentageToMarkComplete=85
NextEpisodePrompt=false
SaveMpvSpeed=true
MpvArgs=[]
MenuOrder=CURRENT,ALL,UNTRACKED,UPDATE,CONTINUE_LAST
SkipRecap=true
ImagePreview=true
AddMissingOptions=true
DiscordClientId=1287457464148820089
SubsLanguage=english
SkipOp=true
SkipEd=true
StoragePath=$HOME/.local/share/curd
AnimeNameLanguage=english
