SubOrDub=sub
SkipFiller=true
RofiSelection=false
ScoreOnCompletion=true
AlternateScreen=true
DiscordPresence=true
Player=mpv
PercentageToMarkComplete=85
NextEpisodePrompt=true
SaveMpvSpeed=true
MpvArgs=[--demuxer-readahead-secs=15]
MenuOrder=CONTINUE_LAST,CURRENT,ALL,UNTRACKED,UPDATE,PLANNING,PAUSED,REWATCHING
SkipRecap=true
ImagePreview=true
AddMissingOptions=true
DiscordClientId=1287457464148820089
SubsLanguage=english
SkipOp=false
SkipEd=false
StoragePath=$HOME/.local/share/curd
AnimeNameLanguage=english
